### PR TITLE
Include cased usernames in database

### LINKED ISSUE #57: Usernames are forced lowercase
Usernames are always returned lowercase. They should instead return the result from the Scratch API as properly capitalized. If this makes DB problems just use another column.

### PR DESCRIPTION
**Pull request by Kenny2github**
Closes #57

### CODE REVIEW

**Comment by Kenny2github** [comment]
Untested as of yet, this is provisional work

**Comment by Kenny2github** [comment]
Tested locally, ready for review

**Review by Semisol — COMMENTED** [review]
You should self-review, I'm busy lately.

**Comment by Kenny2github** [comment]
@Semisol I can't give a binding approving review on my own PR, and we currently require review to merge PRs. You could at least give it a cursory review, but if you don't have time for even that then I will relax the review requirement and merge that way. Is that okay?

**Review by Semisol — APPROVED** [review]

**Pull request merged**
