### PR TITLE
Merge to master 2021-05-19

### PR DESCRIPTION
**Pull request by Kenny2github**
* Allows calling from other MW instances (#45)
* Adds paginated app list (part of #33)
* Adds `created_at` field to applications table (#59)

### CODE REVIEW

**Review by Semisol — COMMENTED** [review]
lgtm, tested?

**Review by Semisol — APPROVED** [review]
oh wait i didnt click approve

**Comment by Kenny2github** [comment]
nice

**Comment by Kenny2github** [comment]
yes, tested locally

**Pull request merged**
